spring.application.name=EcoleMusique_API

# Port du Serveur Tomcat
server.port=8082

#Configuration de la BDD
spring.datasource.url=jdbc:mysql://localhost:3306/harmonia
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update